name: Build Images and Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"

      - name: Install Global Packages
        run: |
          npm install -g @angular/cli
          npm install -g node-pre-gyp
          npm install -g typescript@3.8.3

      - name: Build Backend
        working-directory: ./backend
        run: |
          npm install
          tsc
      
      - name: Push Backend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{secrets.HEROKU_USERNAME}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          appdir: ./backend

      - name: Build Client
        working-directory: ./client
        run: |
          npm install --prod
          npm install typescript@3.8.3
          npm run build

      - name: Push Client to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{secrets.HEROKU_USERNAME}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          appdir: ./client
