name: Build and Push GCR
on: [push]
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"

      - name: Install Global Packages
        run: |
          npm install -g node-pre-gyp
          npm install -g typescript@3.8.3

      - name: Build and Push Backend
        working-directory: ./backend
        run: |
          npm run build-aws
          npm run push-aws

      - name: Build and Push Client
        working-directory: ./client
        run: |
          npm run build-aws
          npm run push-aws